// Code generated by "mock"; DO NOT EDIT.
// Mock for github.com/kmio11/codegen/cmd/mock/_sample.Formatter
package sample

type MockFormatter[T Stringable] struct {
	Formatter[T]
	FakeFormat     func(item T) string
	FakeFormatList func(items []T) []string
}

func (m *MockFormatter[T]) Format(a0 T) string {
	return m.FakeFormat(a0)
}

func (m *MockFormatter[T]) FormatList(a0 []T) []string {
	return m.FakeFormatList(a0)
}

type StubFormatter[T Stringable] struct {
	Format     StubFormat[T]
	FormatList StubFormatList[T]
}

func (s *StubFormatter[T]) NewMock() Formatter[T] {
	return &MockFormatter[T]{FakeFormat: s.FakeFormat, FakeFormatList: s.FakeFormatList}
}

func (s *StubFormatter[T]) FakeFormat(a0 T) string {
	return s.Format.R0
}

func (s *StubFormatter[T]) FakeFormatList(a0 []T) []string {
	return s.FormatList.R0
}

type StubFormat[T Stringable] struct {
	R0 string
}

type StubFormatList[T Stringable] struct {
	R0 []string
}
