// Code generated by "mock"; DO NOT EDIT.
// Mock for github.com/kmio11/codegen/cmd/mock/_sample.Repository
package sample

type MockRepository[T any] struct {
	Repository[T]
	FakeGet  func(id string) (T, error)
	FakeList func() ([]T, error)
	FakeSave func(item T) error
}

func (m *MockRepository[T]) Get(a0 string) (T, error) {
	return m.FakeGet(a0)
}

func (m *MockRepository[T]) List() ([]T, error) {
	return m.FakeList()
}

func (m *MockRepository[T]) Save(a0 T) error {
	return m.FakeSave(a0)
}

type StubRepository[T any] struct {
	Get  StubGet[T]
	List StubList[T]
	Save StubSave[T]
}

func (s *StubRepository[T]) NewMock() Repository[T] {
	return &MockRepository[T]{FakeGet: s.FakeGet, FakeList: s.FakeList, FakeSave: s.FakeSave}
}

func (s *StubRepository[T]) FakeGet(a0 string) (T, error) {
	return s.Get.R0, s.Get.R1
}

func (s *StubRepository[T]) FakeList() ([]T, error) {
	return s.List.R0, s.List.R1
}

func (s *StubRepository[T]) FakeSave(a0 T) error {
	return s.Save.R0
}

type StubGet[T any] struct {
	R0 T
	R1 error
}

type StubList[T any] struct {
	R0 []T
	R1 error
}

type StubSave[T any] struct {
	R0 error
}
