// Code generated by "genmock"; DO NOT EDIT.
// Mock for github.com/kmio11/codegen/cmd/genmock/_sample.SomeInterface
package sample

type MockSomeInterface struct {
	SomeInterface
	FakeAdd  func(x int, y int) (int, error)
	FakeName func() string
}

func (m MockSomeInterface) Add(a0 int, a1 int) (int, error) {
	return m.FakeAdd(a0, a1)
}

func (m MockSomeInterface) Name() string {
	return m.FakeName()
}

type StubSomeInterface struct {
	Add  StubAdd
	Name StubName
}

func (s StubSomeInterface) NewMock() SomeInterface {
	return &MockSomeInterface{FakeAdd: s.FakeAdd, FakeName: s.FakeName}
}

func (s StubSomeInterface) FakeAdd(a0 int, a1 int) (int, error) {
	return s.Add.R0, s.Add.R1
}

func (s StubSomeInterface) FakeName() string {
	return s.Name.R0
}

type StubAdd struct {
	R0 int
	R1 error
}

type StubName struct{ R0 string }
