// Code generated by "mock"; DO NOT EDIT.
// Mock for github.com/kmio11/codegen/_examples/mock.Comparer
package sample

type MockComparer[T comparable] struct {
	Comparer[T]
	FakeCompare func(a T, b T) int
	FakeEqual   func(a T, b T) bool
}

func (m *MockComparer[T]) Compare(a0 T, a1 T) int {
	return m.FakeCompare(a0, a1)
}

func (m *MockComparer[T]) Equal(a0 T, a1 T) bool {
	return m.FakeEqual(a0, a1)
}

type StubComparer[T comparable] struct {
	Compare StubCompare[T]
	Equal   StubEqual[T]
}

func (s *StubComparer[T]) NewMock() Comparer[T] {
	return &MockComparer[T]{FakeCompare: s.FakeCompare, FakeEqual: s.FakeEqual}
}

func (s *StubComparer[T]) FakeCompare(a0 T, a1 T) int {
	return s.Compare.R0
}

func (s *StubComparer[T]) FakeEqual(a0 T, a1 T) bool {
	return s.Equal.R0
}

type StubCompare[T comparable] struct {
	R0 int
}

type StubEqual[T comparable] struct {
	R0 bool
}
