// Code generated by "mock"; DO NOT EDIT.
// Mock for github.com/kmio11/codegen/_examples/mock.Converter
package sample

type MockConverter[From any, To any] struct {
	Converter[From, To]
	FakeConvert func(from From) (To, error)
}

func (m *MockConverter[From, To]) Convert(a0 From) (To, error) {
	return m.FakeConvert(a0)
}

type StubConverter[From any, To any] struct {
	Convert StubConvert[From, To]
}

func (s *StubConverter[From, To]) NewMock() Converter[From, To] {
	return &MockConverter[From, To]{FakeConvert: s.FakeConvert}
}

func (s *StubConverter[From, To]) FakeConvert(a0 From) (To, error) {
	return s.Convert.R0, s.Convert.R1
}

type StubConvert[From any, To any] struct {
	R0 To
	R1 error
}
