// Code generated by "mock"; DO NOT EDIT.
// Mock for github.com/kmio11/codegen/_examples/mock.Number
package sample

type MockNumber[T comparable] struct {
	Number[T]
	FakeAdd      func(a T, b T) T
	FakeMultiply func(a T, b T) T
}

func (m *MockNumber[T]) Add(a0 T, a1 T) T {
	return m.FakeAdd(a0, a1)
}

func (m *MockNumber[T]) Multiply(a0 T, a1 T) T {
	return m.FakeMultiply(a0, a1)
}

type StubNumber[T comparable] struct {
	Add      StubAdd[T]
	Multiply StubMultiply[T]
}

func (s *StubNumber[T]) NewMock() Number[T] {
	return &MockNumber[T]{FakeAdd: s.FakeAdd, FakeMultiply: s.FakeMultiply}
}

func (s *StubNumber[T]) FakeAdd(a0 T, a1 T) T {
	return s.Add.R0
}

func (s *StubNumber[T]) FakeMultiply(a0 T, a1 T) T {
	return s.Multiply.R0
}

type StubAdd[T comparable] struct {
	R0 T
}

type StubMultiply[T comparable] struct {
	R0 T
}
