// Code generated by "mock"; DO NOT EDIT.
// Mock for codegen/sample.SomeInterface
package sample

type MockSomeInterface struct {
	SomeInterface
	FakeAdd  func(x int, y int) (int, error)
	FakeName func() string
}

func (m MockSomeInterface) Add(x int, y int) (int, error) {
	return m.FakeAdd(x, y)
}

func (m MockSomeInterface) Name() string {
	return m.FakeName()
}

type StubSomeInterface struct {
	Add  StubAdd
	Name StubName
}

func (s StubSomeInterface) NewMock() SomeInterface {
	return &MockSomeInterface{FakeAdd: s.FakeAdd, FakeName: s.FakeName}
}

func (s StubSomeInterface) FakeAdd(x int, y int) (int, error) {
	return s.Add.R0, s.Add.R1
}

func (s StubSomeInterface) FakeName() string {
	return s.Name.R0
}

type StubAdd struct {
	R0 int
	R1 error
}

type StubName struct {
	R0 string
}
