// Code generated by "interface"; DO NOT EDIT.
// Interface generated from github.com/kmio11/codegen/_examples/interface.CalculatorInterface
package main

type CalculatorInterface interface {
	Add(a int, b int) int
	Divide(a int, b int) (int, error)
	Multiply(a int, b int) int
	Subtract(a int, b int) int
}
