// Code generated by "interface"; DO NOT EDIT.
// Interface generated from github.com/kmio11/codegen/_examples/interface.LoggerInterface
package main

type LoggerInterface interface {
	Debug(message string)
	Error(message string)
	Info(message string)
}
