// Code generated by "interface"; DO NOT EDIT.
// Interface generated from github.com/kmio11/codegen/cmd/interface/_sample.UserServiceInterface
package sample

type UserServiceInterface interface {
	ListUsers() map[string]string
	UpdateUser(id string, name string) error
	CreateUser(id string, name string) error
	DeleteUser(id string) error
	GetUser(id string) (string, error)
}
